# Generated by Django 5.1 on 2024-08-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('headline', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
