# Generated by Django 5.1 on 2024-08-27 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Game', 'Game'), ('Travel', 'Travel'), ('LifeStyle', 'Lifestyle'), ('Tech', 'Tech'), ('Tour', 'Tour'), ('Health', 'Health'), ('Google', 'Google'), ('Fashion', 'Fashion'), ('Eyes', 'Eyes'), ('Hair', 'Hair'), ('Nail', 'Nail'), ('Lips', 'Lips')], max_length=13, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NewsBitApp.tags'),
            preserve_default=False,
        ),
    ]
