# Generated by Django 5.1 on 2024-08-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0002_tags_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
    ]
