# Generated by Django 5.1 on 2024-08-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0003_remove_tags_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='tag',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Game', 'Game'), ('Travel', 'Travel'), ('LifeStyle', 'Lifestyle'), ('Tech', 'Tech'), ('Tour', 'Tour'), ('Health', 'Health'), ('Google', 'Google'), ('Fashion', 'Fashion'), ('Eyes', 'Eyes'), ('Hair', 'Hair'), ('Nail', 'Nail'), ('Lips', 'Lips')], max_length=13, null=True),
        ),
    ]
