# Generated by Django 5.1 on 2024-08-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0004_remove_news_tags_tags_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
    ]
