# Generated by Django 5.1 on 2024-09-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
