# Generated by Django 5.1 on 2024-08-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0005_remove_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NewsBitApp.tags'),
        ),
    ]
