# Generated by Django 5.1 on 2024-08-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0006_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
