# Generated by Django 5.1 on 2024-09-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0008_taga_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taga',
            new_name='Tag',
        ),
    ]
