# Generated by Django 5.1 on 2024-09-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0009_rename_taga_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='news_by_tags', to='NewsBitApp.tag'),
        ),
    ]
