# Generated by Django 5.1 on 2024-08-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0009_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
