# Generated by Django 5.1 on 2024-08-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0010_delete_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tagBackColor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
