# Generated by Django 5.1 on 2024-09-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0010_alter_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
