# Generated by Django 5.1 on 2024-08-27 11:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0012_news_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
