# Generated by Django 5.1 on 2024-09-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0013_remove_news_tags_news_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
    ]
