# Generated by Django 5.1 on 2024-08-27 19:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0014_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
