# Generated by Django 5.1 on 2024-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0014_remove_news_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='NewsBitApp.tag'),
        ),
    ]
