# Generated by Django 5.1 on 2024-09-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0015_news_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('danger', 'danger'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('light', 'light'), ('dark', 'dark'), ('transparent', 'transparent')], default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
