# Generated by Django 5.1 on 2024-08-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0015_news_description1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
    ]
