# Generated by Django 5.1 on 2024-08-27 20:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0016_remove_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
