# Generated by Django 5.1 on 2024-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0017_remove_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Tech', 'Tech')], default='Tech', max_length=50, unique=True),
        ),
    ]
