# Generated by Django 5.1 on 2024-08-28 13:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0018_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
