# Generated by Django 5.1 on 2024-09-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0020_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='headline',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
