# Generated by Django 5.1 on 2024-09-18 09:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0022_about_history_about_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('mission', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='about',
        ),
    ]
