# Generated by Django 5.1 on 2024-08-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0028_alter_category_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tags',
            new_name='tag',
        ),
    ]
