# Generated by Django 5.1 on 2024-08-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0029_delete_tags_rename_tags_category_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='headline',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
