# Generated by Django 5.1 on 2024-08-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0032_tags_remove_category_headline_remove_category_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tagstype',
        ),
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Game', 'Game'), ('Travel', 'Travel'), ('LifeStyle', 'Lifestyle'), ('Tech', 'Tech'), ('Tour', 'Tour'), ('Health', 'Health'), ('Google', 'Google'), ('Fashion', 'Fashion'), ('Eyes', 'Eyes'), ('Hair', 'Hair'), ('Nail', 'Nail'), ('Lips', 'Lips')], default='Tech', max_length=50),
        ),
    ]
