# Generated by Django 5.1 on 2024-08-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0033_remove_tags_tag_remove_tags_tagstype_tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='name',
        ),
    ]
