# Generated by Django 5.1 on 2024-08-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0036_tags_delete_tag1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
