# Generated by Django 5.1 on 2024-08-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0039_alter_category_name_alter_tag_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
