# Generated by Django 5.1 on 2024-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0044_tag_name_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_color',
            field=models.CharField(choices=[('danger', 'danger'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('light', 'light'), ('dark', 'dark'), ('transparent', 'transparent')], default='primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
