# Generated by Django 5.1 on 2024-08-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0048_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tagBackColor',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default='primary', on_delete=django.db.models.deletion.CASCADE, to='NewsBitApp.category'),
            preserve_default=False,
        ),
    ]
