# Generated by Django 5.1 on 2024-08-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0049_remove_news_tagbackcolor_remove_news_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
