# Generated by Django 5.1 on 2024-08-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0054_remove_tag_tag_tag_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
    ]
