# Generated by Django 5.1 on 2024-08-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0055_remove_news_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
    ]
