# Generated by Django 5.1 on 2024-08-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0056_remove_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.ManyToManyField(to='NewsBitApp.category'),
        ),
    ]
