# Generated by Django 5.1 on 2024-08-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0058_remove_tag_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
