# Generated by Django 5.1 on 2024-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0060_news_tags_alter_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Game', 'Game'), ('Travel', 'Travel'), ('LifeStyle', 'Lifestyle'), ('Tech', 'Tech'), ('Tour', 'Tour'), ('Health', 'Health'), ('Fashion', 'Fashion'), ('Eyes', 'Eyes'), ('Hair', 'Hair'), ('Nail', 'Nail'), ('Lips', 'Lips')], default='Tech', max_length=50, unique=True)),
                ('name_color', models.CharField(choices=[('danger', 'danger'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('light', 'light'), ('dark', 'dark'), ('transparent', 'transparent')], default='primary', max_length=50)),
            ],
        ),
    ]
