# Generated by Django 5.1 on 2024-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0061_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='news',
            name='editor_choice',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
