# Generated by Django 5.1 on 2024-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsBitApp', '0062_delete_tag_news_editor_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='posts',
            field=models.IntegerField(default=0),
        ),
    ]
